parameters:
    darvin_config.parameter.repository.class:  Darvin\ConfigBundle\Repository\ParameterRepository
    darvin_config.parameter.repository.entity: DarvinConfigBundle:ParameterEntity

    darvin_config.parameter.value_converter.class: Darvin\ConfigBundle\Parameter\ParameterValueConverter

services:
    darvin_config.parameter.repository:
        alias: '%darvin_config.parameter.repository.class%'

    '%darvin_config.parameter.repository.class%':
        class: '%darvin_config.parameter.repository.class%'
        arguments:
            - '@doctrine'
            - '%darvin_config.parameter.repository.entity%'
        tags:
            - { name: doctrine.repository_service }

    darvin_config.parameter.value_converter:
        class: '%darvin_config.parameter.value_converter.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
