parameters:
    darvin_config.parameter.repository.class:  Darvin\ConfigBundle\Repository\ParameterRepository
    darvin_config.parameter.repository.entity: DarvinConfigBundle:Parameter

services:
    darvin_config.parameter.repository:
        class:   %darvin_config.parameter.repository.class%
        factory: [ "@doctrine.orm.entity_manager", getRepository ]
        arguments:
            - %darvin_config.parameter.repository.entity%
